### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by chisatom0908** [chisatom0908/furima-39585#21]
# フリマアプリのURL
https://furima-39585.onrender.com/
# Basic認証のIDとパスワード
ID: admin
Password: 2222
# 出品者用のメールアドレスとパスワード
Email: test1@tt
Password: test111
# 購入者用のメールアドレスとパスワード
Email: test2@tt
Password: test222

**Comment by motomuun** [comment]
@chisatom0908 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [ ] **発送元の地域は、「---」と47都道府県の合計48項目が表示されること（--- は初期値として設定すること）**
「県」まで表示されるように修正をお願いします。
<img width="302" alt="スクリーンショット 2023-08-15 16 22 07" src="https://github.com/chisatom0908/furima-39585/assets/65059944/36f14881-6c11-42ef-a6e2-1ff6ed546e32">

- [ ] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
販売価格を入力しても、販売手数料や販売利益が変わりません。入力内容に応じて変わるように修正をお願いします。

**商品購入機能の確認**

- [ ] **クレジットカード情報は必須であり、PAY.JPテストカードの情報で決済ができること**
クレジットカード情報を入力するフォームに文字や数字を打ち込むことが出来ません。入力できるように修正をお願いします。


※購入後の機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by chisatom0908** [comment]
ご確認ありがとうございました。
ご指摘頂いた3件について修正いたしました。再確認よろしくお願いいたします。

**Comment by snkw-works** [comment]
@chisatom0908 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点について一部を除き修正が確認できました。ありがとうございます。
引き続き、修正していただきたい箇所がございましたので、以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **商品出品ページにて、入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう(JavaScriptを使用して実装すること)**
入力に問題がある状態で出品するボタンをクリックした後のページで、販売手数料や販売利益が表示されない状態です。

https://github.com/chisatom0908/furima-39585/assets/54050089/4e0811d1-d8a1-4b3f-a118-8189c70cfa6b

- [ ] **商品購入ページにて、クレジットカードの情報が入力できるよう修正しましょう**
入力に問題がある状態で購入ボタンをクリックした後のページで、クレジットカードの情報入力欄は表示されていますが、カーソルを合わせても入力ができない状態です。

https://github.com/chisatom0908/furima-39585/assets/54050089/e38ed642-e26b-4459-8c7a-b17b7773f6e2


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら、以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by chisatom0908** [comment]
ご確認ありがとうございました。
ご指摘頂いた2件について修正いたしました。再確認よろしくお願いいたします。

**Comment by motomuun** [comment]
@chisatom0908 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
